name: Build ipa

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2

     - name: Install Theos
       uses: Randomblock1/theos-action@v1.4
     
     - name: build ipa
       run:  |
            make
     
     - name: Upload artifact
       uses: actions/upload-artifact@v4.5.0
       with:
        name: EnableQUIC
        path: EnableQUIC.ipa
